### ISSUE TITLE
CSV DUMP Error: KeyError: 'entities'

### ISSUE THREAD

**Issue by shivdhwaj** [wakatime/wakadump#9]
```
Getting column names...  [------------------------------------]    0%
Traceback (most recent call last):
  File "/usr/local/bin/wakadump", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wakadump/cli.py", line 56, in main
    formatter.run()
  File "/usr/local/lib/python2.7/dist-packages/wakadump/formats/csv.py", line 28, in run
    self._get_column_names()
  File "/usr/local/lib/python2.7/dist-packages/wakadump/formats/csv.py", line 68, in _get_column_names
    self._find_columns(self.entities, day['entities'])
KeyError: 'entities'
```

**Comment by alanhamlett** [comment]
Fixed in v4.0.0. Thanks for reporting this!
